# Generated by Django 4.1.7 on 2023-03-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='text',
            field=models.TextField(),
        ),
    ]
