# Generated by Django 4.1.7 on 2023-03-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csv_files/'),
        ),
        migrations.AddField(
            model_name='user',
            name='csv_file_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='csv_file_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
