# Generated by Django 4.1.7 on 2023-03-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_csv_file_user_csv_file_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'CSV'},
        ),
    ]
